import React from "react";
import type {Metadata} from "next";
import "./globals.css";
import ThemeToggle from "@/app/components/Toggle/ThemeToggle";
import {ThemeProvider} from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
    <body>
    <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
      <ThemeToggle/>
      {children}
    </ThemeProvider>
    </body>
    </html>
  );
}
